export const GET_PHOTOS_REQUEST = "PAGE/GET_PHOTOS_REQUEST";
export const GET_PHOTOS_SUCCESS = "PAGE/GET_PHOTOS_SUCCESS";

export const LOGIN_REQUEST = "USER/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USER/LOGIN_SUCCESS";
export const LOGIN_FAIL = "USER/LOGIN_FAIL";
