export const GET_PHOTOS_REQUEST = "PAGE/GET_PHOTOS_REQUEST";
export const GET_PHOTOS_SUCCESS = "PAGE/GET_PHOTOS_SUCCESS";
export const GET_PHOTOS_FAIL = "PAGE/GET_PHOTOS_FAIL";

export const LOGIN_REQUEST = "USER/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USER/LOGIN_SUCCESS";
export const LOGIN_FAIL = "USER/LOGIN_FAIL";

export const LOGOUT_REQUEST = "USER/LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "USER/LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "USER/LOGOUT_FAIL";
export const SET_SEARCH_MID = "USER/SET_SEARCH_MID";
